
package System1;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Farah
 */
public class DeletePanel extends javax.swing.JPanel {
    StudentsDB studentsDB = new StudentsDB("students.txt");
    AdminRole user = new AdminRole(studentsDB);
    List<Student> students = user.ViewStudents();

    public DeletePanel() {
        initComponents();
        loadStudentsToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        StudentsTable = new javax.swing.JTable();
        DeleteBtn = new javax.swing.JButton();

        StudentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Gender", "Dep.", "GPA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(StudentsTable);

        DeleteBtn.setText("DELETE");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeleteBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadStudentsToTable() {
        DefaultTableModel model = (DefaultTableModel) StudentsTable.getModel();
        model.setRowCount(0);
        for (Student student : students) {
            int studentId = student.getStudent_ID();
            String fullName = student.getFull_Name();
            int age = student.getAge();
            String gender = student.getGender();
            String department = student.getDepartment();
            float gpa = student.getGPA();
            model.addRow(new Object[] { studentId, fullName, age, gender, department, gpa });
        }
    }

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DeleteBtnActionPerformed
        int row = StudentsTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "No row was selected!", "Select row", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this student?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        } else {
            try {
                int studentId = (Integer) StudentsTable.getValueAt(row, 0);
                boolean deleted = user.DeleteStudent(studentId);

                if (deleted) {
                    try {
                        studentsDB.saveToFile();
                    } catch (IllegalArgumentException e) {
                        JOptionPane.showMessageDialog(this, "Error saving changes to file: " + e.getMessage(), "Error",
                                JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    
                    DefaultTableModel model = (DefaultTableModel) StudentsTable.getModel();
                    model.removeRow(row);
                    JOptionPane.showMessageDialog(this, "Student deleted successfully!", "Success",
                            JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to delete student!", "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error deleting student: " + ex.getMessage(), "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }// GEN-LAST:event_DeleteBtnActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTable StudentsTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
