/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package System1;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yasmin Haytham
 */
public class SAUPanel extends javax.swing.JPanel {
    private ArrayList<Student> students;
    private StudentsDB database;
    public SAUPanel() {
        initComponents();
        jScrollPane1.setVisible(false);
        database = new StudentsDB("Students.txt");
        students = this.database.returnAllRecords();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        NameOrID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentsTable = new javax.swing.JTable();

        jLabel2.setText("Search By ID or Name:");
        NameOrID.setText("");
        NameOrID.setPreferredSize(new java.awt.Dimension(200, 30));
        NameOrID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameOrIDActionPerformed(evt);
            }
        });

        StudentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Full Name", "Age", "Gender", "Department", "GPA/Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(StudentsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameOrID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameOrID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NameOrIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameOrIDActionPerformed
       String searchText = NameOrID.getText().trim(); 
       if (searchText.isEmpty())
       {
          JOptionPane.showMessageDialog(this, "Field is EMPTY !!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
          return;
       }
       
       loadStudentsToTable(searchText);
       
    }//GEN-LAST:event_NameOrIDActionPerformed

private void loadStudentsToTable(String searchText) {
        DefaultTableModel model = (DefaultTableModel) StudentsTable.getModel();
        model.setRowCount(0);
        boolean flag =false;
        if (students.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Students File is Empty", "ERROR", JOptionPane.INFORMATION_MESSAGE);  
          return;
        }
        
        for (Student student : students) {
            if (student.lineRepresentation().toLowerCase().contains(searchText.toLowerCase()))
            {
                flag=true;
            int studentId = student.getStudent_ID();
            String fullName = student.getFull_Name();
            int age = student.getAge();
            String gender = student.getGender();
            String department = student.getDepartment();
            float gpa = student.getGPA();
            model.addRow(new Object[] { studentId, fullName, age, gender, department, gpa });
        }
    }
    if (flag)
    {
          jScrollPane1.setVisible(true);
        
        // FORCE REFRESH - Add these lines:
        jScrollPane1.revalidate();
        jScrollPane1.repaint();
        StudentsTable.revalidate();
        StudentsTable.repaint();
        this.revalidate();
        this.repaint();
    }
    else
        {
            JOptionPane.showMessageDialog(this, "Student NOT FOUND\nIncorrect ID or Name", "NOT FOUND", JOptionPane.INFORMATION_MESSAGE);  
            jScrollPane1.setVisible(false);
            return;
        }
        
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NameOrID;
    private javax.swing.JTable StudentsTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}